import fs from "node:fs";
import path from "node:path";

const here = path.dirname(new URL(import.meta.url).pathname);
const root = path.resolve(here, "../..");
const out = path.resolve(here, "../public/data/explorer.json");
const json = (file) => { try { return JSON.parse(fs.readFileSync(file, "utf8")); } catch { return null; } };
const jsonl = (file) => { try { return fs.readFileSync(file, "utf8").split(/\r?\n/).filter(Boolean).map(JSON.parse); } catch { return []; } };
const csv = (file) => { try { const [head,...lines]=fs.readFileSync(file,"utf8").trim().split(/\r?\n/); const keys=head.split(","); return lines.map(line=>Object.fromEntries(line.split(",").map((v,i)=>[keys[i],v]))); } catch { return []; } };
const run = (name) => path.join(root, "lab_runs", name);
const confirmation = json(path.join(run("fresh_confirmation"), "results.json")) || {};
const backtest = json(path.join(run("safety_backtest"), "results.json")) || {};
const sealed = json(path.join(run("sealed_safety"), "results.json"));
const sealedCases = jsonl(path.join(run("sealed_safety"), "cases.jsonl"));
const sealedSynth = jsonl(path.join(run("sealed_safety"), "syntheses.jsonl"));
const cases = sealedCases.length ? sealedCases : jsonl(path.join(run("fresh_confirmation"), "cases.jsonl"));
const syntheses = sealedSynth.length ? sealedSynth : jsonl(path.join(run("fresh_confirmation"), "syntheses.jsonl"));
const source = sealedCases.length && sealedSynth.length ? "sealed_safety" : "fresh_confirmation";
const byCase = new Map();
for (const row of syntheses) byCase.set(row.case_id, [...(byCase.get(row.case_id)||[]), row.result||row]);
const causal = backtest?.strategies?.expanding_top_decile_warmup20 || {};
const selected = new Set(causal.tickers || confirmation?.strategies?.safety_first?.tickers || []);
const global = new Set(backtest?.strategies?.global_top_decile_noncausal?.tickers || []);
const mean = (xs) => { const a=xs.map(Number).filter(Number.isFinite); return a.length?a.reduce((x,y)=>x+y,0)/a.length:null; };
let trades = cases.filter(c=>selected.has(c.ticker) && (!c.source_run_dir || String(c.source_run_dir).includes("fresh_long"))).map(c=>{
  const synth=byCase.get(c.case_id)||[], downside=mean(synth.map(s=>s.downside_tail_probability_pct));
  const returns=c.returns||c.outcome||{};
  const entryDate=c.market_at_cutoff?.entry_date||c.cutoff;
  const exitDate=c.horizon_end||new Date(+new Date(`${entryDate}T12:00:00Z`)+90*86400000).toISOString().slice(0,10);
  return { id:c.case_id,ticker:c.ticker,company:c.company,signalDate:c.cutoff,entryDate,exitDate,holdingDays:90,strategy:"Expanding safety threshold",causalSelected:true,alsoGlobalTopDecile:global.has(c.ticker),downsideProbability:downside,safetyScore:downside==null?null:100-downside,expectedExcessReturn:mean(synth.map(s=>s.expected_excess_return_90d_pct)),positiveProbability:mean(synth.map(s=>s.probability_positive_excess_90d_pct)),stockReturn:returns.stock_return_90d??null,benchmarkReturn:returns.spy_return_90d??null,excessReturn:returns.relative_return_90d??null,thesis:synth[0]?.thesis||"No synthesis narrative available.",catalyst:synth[0]?.catalyst||"No dated catalyst identified.",invalidation:synth[0]?.invalidation||"No invalidation recorded.",evidence:synth.flatMap(s=>s.evidence_refs||[]).slice(0,6),references:(c.snapshot_sources||[]).map(s=>({form:s.form,filed:s.date,accession:s.accession,url:s.accession&&c.cik?`https://www.sec.gov/Archives/edgar/data/${String(c.cik).replace(/^0+/,"")}/${s.accession.replaceAll("-","")}/`:null})),modelReplicates:synth.length,anchorForm:c.anchor_form,anchorAccession:c.anchor_accession,selectionNote:c.selection_note };
}).sort((a,b)=>a.signalDate.localeCompare(b.signalDate)||a.ticker.localeCompare(b.ticker));
if (sealed?.trades?.length) trades=sealed.trades.map((t,i)=>({id:t.trade_id||t.case_id||`sealed-${i}`,ticker:t.ticker,company:t.company||t.name||t.ticker,signalDate:t.signal_date||t.cutoff||t.date,entryDate:t.entry_date||t.signal_date||t.cutoff,exitDate:t.exit_date||t.horizon_end,holdingDays:t.holding_days||90,strategy:t.strategy||"Sealed safety strategy",causalSelected:true,alsoGlobalTopDecile:false,downsideProbability:t.downside_probability_pct??t.downside_tail_probability_pct??null,safetyScore:t.safety_score??(t.downside_probability_pct==null?null:100-t.downside_probability_pct),expectedExcessReturn:t.expected_excess_return_90d_pct??null,positiveProbability:t.probability_positive_excess_90d_pct??null,stockReturn:t.stock_return??t.stock_return_90d??null,benchmarkReturn:t.benchmark_return??t.spy_return_90d??null,excessReturn:t.excess_return??t.relative_return_90d??null,thesis:t.thesis||t.reason||"No thesis supplied.",catalyst:t.catalyst||"No catalyst supplied.",invalidation:t.invalidation||"No invalidation supplied.",evidence:t.evidence||t.evidence_refs||[],references:t.references||t.snapshot_sources||[],modelReplicates:t.model_replicates??null}));
const daily=csv(path.join(run("safety_backtest"),"daily_portfolio.csv"));
const portfolio=daily.filter((_,i)=>i%5===0||i===daily.length-1).map(d=>({date:d.date,nav:+d.nav,exposure:+d.exposure,activePositions:+d.active_positions}));
const strategy=sealed?.strategy||sealed?.summary||causal;
const metrics={cagr:strategy.cagr??causal.cagr??null,sharpe:strategy.sharpe_over_13week_tbill??strategy.sharpe??causal.sharpe_over_13week_tbill??null,maxDrawdown:strategy.max_drawdown??causal.max_drawdown??null,trades:strategy.trades??trades.length,winRate:strategy.trade_win_rate??causal.trade_win_rate??null,terminalReturn:strategy.terminal_return??causal.terminal_return??null,averageExposure:strategy.average_capital_exposure??causal.average_capital_exposure??null,start:strategy.start??causal.start??trades[0]?.signalDate??null,end:strategy.end??causal.end??trades.at(-1)?.exitDate??null};
const dates=[...new Set(trades.map(t=>t.signalDate).filter(Boolean))].sort();
const payload={generatedAt:new Date().toISOString(),source,sealedAvailable:Boolean(sealed),strategyName:"Safety-first · causal expanding threshold",strategyDescription:"Among severe-drawdown filing events, buy only candidates whose model-implied downside-tail risk clears a threshold estimated from prior signals. Equal-sized positions enter after the filing and hold for 90 days.",execution:backtest.execution||{},metrics,dates,trades,portfolio,limitations:sealed?.limitations||backtest.limitations||[]};
fs.mkdirSync(path.dirname(out),{recursive:true}); fs.writeFileSync(out,JSON.stringify(payload,null,2)+"\n");
console.log(`Exported ${trades.length} trades across ${dates.length} dates from ${source}.`);
