"use client";
import { useEffect, useMemo, useState } from "react";
type Trade={id:string;ticker:string;company:string;signalDate:string;entryDate:string;exitDate:string;holdingDays:number;safetyScore:number|null;downsideProbability:number|null;expectedExcessReturn:number|null;stockReturn:number|null;benchmarkReturn:number|null;excessReturn:number|null;thesis:string;catalyst:string;invalidation:string;evidence:{role?:string;semantic_key?:string;why?:string}[];references:{form?:string;filed?:string;accession?:string;url?:string}[];modelReplicates:number|null;alsoGlobalTopDecile:boolean};
type Data={generatedAt:string;source:string;sealedAvailable:boolean;strategyDescription:string;metrics:Record<string,number|string|null>;dates:string[];trades:Trade[];portfolio:{date:string;nav:number}[];limitations:string[]};
const fp=(v:number|null|undefined,d=1)=>v==null?"—":`${(v*100).toFixed(d)}%`,mp=(v:number|null|undefined)=>v==null?"—":`${v.toFixed(1)}%`,fd=(v:string)=>new Date(`${v}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
function Chart({rows}:{rows:Data["portfolio"]}){const bars=rows.filter((_,i)=>i%Math.max(1,Math.floor(rows.length/70))===0),vals=bars.map(x=>x.nav),min=Math.min(...vals),max=Math.max(...vals);return <div className="chart"><div className="bars">{bars.map(x=><i key={x.date} style={{height:`${18+82*(x.nav-min)/(max-min||1)}%`}} title={`${x.date}: ${x.nav.toFixed(3)}`}/>)}</div><div className="axis"><span>{rows[0]?.date}</span><span>Growth of $1</span><span>{rows.at(-1)?.date}</span></div></div>}
export default function Home(){
 const [data,setData]=useState<Data|null>(null),[idx,setIdx]=useState(0),[chosen,setChosen]=useState<string|null>(null);
 useEffect(()=>{fetch("/data/explorer.json").then(r=>r.json()).then((d:Data)=>{setData(d);setIdx(Math.max(0,d.dates.length-1))})},[]);
 const date=data?.dates[idx],trades=useMemo(()=>data?.trades.filter(t=>t.signalDate===date)||[],[data,date]),selected=data?.trades.find(t=>t.id===chosen)||trades[0]||null;
 useEffect(()=>{if(trades.length&&!trades.some(t=>t.id===chosen))setChosen(trades[0].id)},[date,trades,chosen]);
 if(!data)return <main className="loading">Loading research ledger…</main>;
 const nearest=(target:string)=>{let best=0,gap=Infinity;data.dates.forEach((d,i)=>{const x=Math.abs(+new Date(d)-+new Date(target));if(x<gap){best=i;gap=x}});setIdx(best)};
 return <main><header className="topbar"><div className="brand"><b>AH</b><span>Alpha Hunt</span><em>/</em><span>Trade explorer</span></div><div className="status"><i/>{data.sealedAvailable?"Sealed evaluation":"Research confirmation"}<span>Updated {new Date(data.generatedAt).toLocaleDateString()}</span></div></header>
 <section className="hero"><div><p className="eyebrow">POINT-IN-TIME RESEARCH LEDGER</p><h1>What did the model know<br/>on <em>{date?fd(date):"this date"}</em>?</h1><p className="intro">Inspect every proposed long, the filing evidence behind it, and what happened over the next 90 days.</p></div><div className="metricStrip"><div><span>Causal Sharpe</span><strong>{Number(data.metrics.sharpe).toFixed(2)}</strong><small>vs. 13-week T-bill</small></div><div><span>CAGR</span><strong>{fp(Number(data.metrics.cagr))}</strong><small>{data.metrics.start} — {data.metrics.end}</small></div><div><span>Max drawdown</span><strong className="neg">{fp(Number(data.metrics.maxDrawdown))}</strong><small>{data.metrics.trades} executed trades</small></div></div></section>
 <section className="time"><div><span>Signal date</span><strong>{date?fd(date):"—"}</strong></div><label>Jump to date<input type="date" value={date||""} min={data.dates[0]} max={data.dates.at(-1)} onChange={e=>nearest(e.target.value)}/></label><input aria-label="Signal date timeline" type="range" min="0" max={Math.max(0,data.dates.length-1)} value={idx} onChange={e=>setIdx(+e.target.value)}/><div className="timeAxis"><span>{fd(data.dates[0])}</span><span>{data.dates.length} signal dates</span><span>{fd(data.dates.at(-1)!)}</span></div></section>
 <div className="workspace"><aside><div className="sectionTitle"><div><span>Proposed longs</span><b>{trades.length}</b></div><small>Nearest selected date</small></div>{trades.map(t=><button key={t.id} className={selected?.id===t.id?"active":""} onClick={()=>setChosen(t.id)}><strong>{t.ticker}</strong><span>{t.company}<small>Safety {t.safetyScore?.toFixed(0)??"—"} / 100</small></span><em className={Number(t.excessReturn)>=0?"pos":"neg"}>{fp(t.excessReturn)}<small>excess</small></em></button>)}</aside>
 {selected&&<article><div className="tradeHead"><div><div className="tickerLine"><strong>{selected.ticker}</strong><span>LONG</span>{selected.alsoGlobalTopDecile&&<span className="quiet">TOP-DECILE SAFETY</span>}</div><h2>{selected.company}</h2><p>Signal generated {fd(selected.signalDate)} · {selected.modelReplicates??"—"} independent model reads</p></div><div className="outcome"><span>90-day excess return</span><strong className={Number(selected.excessReturn)>=0?"pos":"neg"}>{fp(selected.excessReturn)}</strong><small>{fp(selected.stockReturn)} stock · {fp(selected.benchmarkReturn)} SPY</small></div></div>
 <div className="scores"><div><span>Safety score</span><strong>{selected.safetyScore?.toFixed(0)??"—"}<small>/100</small></strong><div className="meter"><i style={{width:`${selected.safetyScore||0}%`}}/></div></div><div><span>Downside-tail risk</span><strong>{mp(selected.downsideProbability)}</strong><small>model probability</small></div><div><span>Expected excess</span><strong>{selected.expectedExcessReturn==null?"—":`${selected.expectedExcessReturn.toFixed(1)}%`}</strong><small>at signal time</small></div><div><span>Holding window</span><strong>{selected.holdingDays}d</strong><small>{fd(selected.entryDate)} → {fd(selected.exitDate)}</small></div></div>
 <section className="narrative"><p className="eyebrow">MODEL THESIS · AS OF {selected.signalDate}</p><h3>Why it cleared the safety filter</h3><p>{selected.thesis}</p></section><div className="notes"><section><b>Catalyst</b><p>{selected.catalyst}</p></section><section><b>Invalidation</b><p>{selected.invalidation}</p></section></div>
 <section className="evidence block"><div className="sectionTitle"><div><span>Grounded evidence</span><b>{selected.evidence.length}</b></div><small>Claims cited by synthesis</small></div><div>{selected.evidence.map((e,i)=><section key={`${e.semantic_key}-${i}`}><span>{e.role||"filing"}</span><strong>{(e.semantic_key||"Evidence").replaceAll("_"," ")}</strong><p>{e.why}</p></section>)}</div></section>
 <section className="filings block"><div className="sectionTitle"><div><span>Point-in-time filing set</span><b>{selected.references.length}</b></div><small>Available by signal date</small></div>{selected.references.map((r,i)=><a href={r.url||"#"} target="_blank" rel="noreferrer" key={`${r.accession}-${i}`}><b>{r.form}</b><span>Filed {r.filed}</span><code>{r.accession}</code><em>View SEC ↗</em></a>)}</section></article>}</div>
 <section className="portfolio"><div><p className="eyebrow">PORTFOLIO CONTEXT</p><h2>${(1+Number(data.metrics.terminalReturn)).toFixed(2)} ending value</h2><p>Growth of $1 under the causal expanding-threshold rule, with idle capital earning the historical 13-week Treasury yield.</p><div className="mini"><div><span>Win rate</span><strong>{fp(Number(data.metrics.winRate))}</strong></div><div><span>Avg. exposure</span><strong>{fp(Number(data.metrics.averageExposure))}</strong></div><div><span>Total return</span><strong>{fp(Number(data.metrics.terminalReturn))}</strong></div></div></div><Chart rows={data.portfolio}/></section>
 <section className="method"><div><p className="eyebrow">READ THIS CORRECTLY</p><h2>A research result,<br/>not a recommendation.</h2></div><div><p>{data.strategyDescription}</p><ul>{data.limitations.slice(0,4).map(x=><li key={x}>{x}</li>)}</ul></div></section><footer><span>Alpha Hunt · Bitemporal filing research</span><span>Source: {data.source.replaceAll("_"," ")} · Generated {new Date(data.generatedAt).toLocaleString()}</span></footer></main>
}
